version: '3.6'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: mba
      MONGODB_DATABASE: nestly
      MONGODB_PASS: supersafepassword
    ports:
      - "12345:27017"