version: '3.6'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: mba
      MONGODB_DATABASE: nestly
      MONGODB_PASS: supersafepassword
  backend:
    image: nestly
    environment:
      - BASE_URL=https://locahost:3001
      - DB_HOST=db
      - DB_PORT=27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - db
    restart: unless-stopped